### ISSUE TITLE
make 出错

### ISSUE THREAD

**Issue by andy236726493** [swoole/ext-postgresql#10]
In file included from /home/ext-postgresql-master/swoole_postgresql_coro.cc:17:0:
/home/ext-postgresql-master/swoole_postgresql_coro.h:28:33: 致命错误：postgresql/libpq-fe.h：没有那个文件或目录
 #include <postgresql/libpq-fe.h>
                                 ^

**Comment by yunnian** [comment]
您好 ，需要确保系统中已安装libpq库
mac安装完postgresql自带libpq库，环境之间有差异，ubuntu可能需要apt-get install libpq-dev
也可以单独指定libpq库目录如：./configure --with-libpq-dir=/etc/postgresql

另外如果还报include 错误，尝试改为： include <libpq-fe.h> 试下

**Comment by andy236726493** [comment]
改 include <libpq-fe.h>, make 可以了
