### ISSUE TITLE
Any plans to support Swoole 4.5.0 for this extension?

### ISSUE THREAD

**Issue by codercms** [swoole/ext-postgresql#22]
Hello, guys!
I see there was some progress for supporting Swoole 4.5.0 on the master branch, but it was months ago.
Do you have any plans for this? Or maybe you can share a manual or an example of how to upgrade Swoole extensions to 4.5.0

**Comment by codercms** [comment]
@sy-records FYI

**Comment by sy-records** [comment]
Upgrade swoole extension or swoole_postgresql extension?

**Comment by codercms** [comment]
@sy-records I mean swoole_postgresql extension

**Comment by sy-records** [comment]
Well, I need to ask.

**Comment by codercms** [comment]
@sy-records do you have any news?

**Comment by codercms** [comment]
Closing this issue, since the release is created https://github.com/swoole/ext-postgresql/releases/tag/v4.4.18

@matyhtf thanks
