### ISSUE TITLE
Unable to load dynamic library 'swoole_postgresql.so'

### ISSUE THREAD

**Issue by yolao** [swoole/ext-postgresql#26]
After run 'make test'
Warning: PHP Startup: Unable to load dynamic library 'swoole_postgresql.so'

**Comment by yolao** [comment]
Warning: PHP Startup: Unable to load dynamic library 'swoole_postgresql.so' (tried: /home/medard5/sox/ext-postgresql/modules/swoole_postgresql.so (/home/medard5/sox/ext-postgresql/modules/swoole_postgresql.so: undefined symbol: SwooleG), /home/medard5/sox/ext-postgresql/modules/swoole_postgresql.so.so (/home/medard5/sox/ext-postgresql/modules/swoole_postgresql.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0

**Comment by sy-records** [comment]
Executing the `make test` will copy a `tmp-php.ini` file, which does not have the `swoole` extension loaded in it, so it will report an error.

There's no need to execute `make test`, After you have successfully used `make install`, just modify `php.ini`.
