### ISSUE TITLE
新版swoole和这个不匹配呢

### ISSUE THREAD

**Issue by linjuchen** [swoole/ext-postgresql#45]
In file included from /data/opt/ext-postgresql-4.4.18/swoole_postgresql_coro.cc:17:0:
/data/opt/ext-postgresql-4.4.18/swoole_postgresql_coro.h:27:2: error: #error "Ext version does not match the Swoole version"
 #error "Ext version does not match the Swoole version"
  ^
/data/opt/ext-postgresql-4.4.18/swoole_postgresql_coro.cc:59:5: error: ‘php_coro_context’ does not name a type
     php_coro_context context;
     ^
/data/opt/ext-postgresql-4.4.18/swoole_postgresql_coro.cc:73:18: error: ‘php_coro_context’ does not name a type
 static sw_inline php_coro_context * php_swoole_postgresql_coro_get_context(zval *zobject)
                  ^
/data/opt/ext-postgresql-4.4.18/swoole_postgresql_coro.cc: In function ‘void zim_swoole_postgresql_coro_connect(zend_execute_data*, zval*)’:
/data/opt/ext-postgresql-4.4.18/swoole_postgresql_coro.cc:280:5: error: ‘string’ is not a member of ‘zend’
     zend::string dsn(conninfo);

**Comment by Xuan-Goldenf** [comment]
直接拉git master的版本
