### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by linjuchen** [swoole/ext-postgresql#47]
![图片](https://user-images.githubusercontent.com/33847736/95077484-2a142300-0746-11eb-9d47-5eca4a2e1a78.png)

**Comment by sy-records** [comment]
需要安装`libpq`库，参考[文档](https://wiki.swoole.com/#/coroutine_client/postgresql?id=%e7%bc%96%e8%af%91%e5%ae%89%e8%a3%85)
