### ISSUE TITLE
swoole master拿来编译出错

### ISSUE THREAD

**Issue by linjuchen** [swoole/ext-postgresql#50]
![图片](https://user-images.githubusercontent.com/33847736/99140103-86d5f800-2679-11eb-8431-d4d6c9d31aa5.png)

请帮忙看看 哪里的问题。

**Comment by sy-records** [comment]
swoole版本和扩展版本不一致; 没有libpq库

**Comment by linjuchen** [comment]
![图片](https://user-images.githubusercontent.com/33847736/99160997-484b4680-2728-11eb-8d48-907d6bad148f.png)

**Comment by sy-records** [comment]
没有libpq库... https://wiki.swoole.com/#/coroutine_client/postgresql?id=%e7%bc%96%e8%af%91%e5%ae%89%e8%a3%85

**Comment by linjuchen** [comment]
![图片](https://user-images.githubusercontent.com/33847736/99161453-96af1400-272d-11eb-81f0-f697b1fd986b.png)

**Comment by linjuchen** [comment]
![图片](https://user-images.githubusercontent.com/33847736/99161516-20f77800-272e-11eb-9051-3dce0c98bd53.png)

**Comment by sy-records** [comment]
不要提多个issue... #34 #45 #47 这几个关了吧

**Comment by linjuchen** [comment]
其他关闭了。这个咋弄呢。

**Comment by sy-records** [comment]
升级下版本试试，9.3+

**Comment by linjuchen** [comment]
已经解决。

**Comment by ifsure** [comment]
> 已经解决。

麻烦问下怎么解决的。同样遇到这个问题
