### ISSUE TITLE
Can't compile on 4.6.6 or newer

### ISSUE THREAD

**Issue by ipejasinovic** [swoole/ext-postgresql#59]
I'm running swoole:4.6.5-php8.0 docker image and compile from source ext-postgresql extension. All fine, but as of version 4.6.6 I can't compile extension. Says php_swoole.h: No such file or directory.

**Comment by sy-records** [comment]
Thank you for your feedback. This issue has been fixed. https://github.com/swoole/swoole-src/pull/4239

The v4.7 version will fix it, and you can now compile master for use.
