### ISSUE TITLE
swoole  4.4.8 开启 postgresql 协程，编译 swoole   --enable-coroutine-postgresql 出错，

### ISSUE THREAD

**Issue by andy236726493** [swoole/ext-postgresql#72]
swoole v4.4.8 开启 postgresql 协程，编译 swoole   --enable-coroutine-postgresql 出错，

swoole v4.4.8  现在编译  支持postgresql 协程，需要 加什么  ./configure --help 里看不到

**Comment by andy236726493** [comment]
不是v4.4.8，是swoole V4.8.8, 这个版本是不是，已经包含 postgresql 客户端了

**Comment by sy-records** [comment]
master v5.0 增加编译参数可以开启。
低版本还需要编译这个扩展
